# Generated by Django 2.0 on 2018-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('project_description', models.TextField(verbose_name='项目描述')),
                ('add_date', models.DateTimeField(verbose_name='添加时间')),
                ('project_author', models.CharField(max_length=50, verbose_name='项目作者')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
    ]
