# Generated by Django 2.0 on 2018-02-04 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(default='', verbose_name='github地址'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='project_img/default.jpg', upload_to='project_img/%Y/%m', verbose_name='项目封面'),
        ),
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(default='', verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 10, 48, 56, 152987), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default='', verbose_name='项目描述'),
        ),
    ]
