# Generated by Django 2.0 on 2018-02-19 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180204_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 20, 7, 55, 269562), verbose_name='添加时间'),
        ),
    ]
