# Generated by Django 2.0 on 2018-02-22 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20180219_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 10, 35, 20, 771961), verbose_name='添加时间'),
        ),
    ]
