# Generated by Django 2.0 on 2018-02-22 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20180222_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 11, 9, 40, 966025), verbose_name='添加时间'),
        ),
    ]
