# Generated by Django 2.0 on 2018-02-22 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20180222_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 12, 49, 6, 496495), verbose_name='添加时间'),
        ),
    ]
