# Generated by Django 2.0 on 2018-02-22 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20180222_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 14, 51, 41, 321668), verbose_name='添加时间'),
        ),
    ]
