# Generated by Django 2.0 on 2018-02-22 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20180222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 15, 15, 27, 866437), verbose_name='添加时间'),
        ),
    ]
