# Generated by Django 2.0 on 2018-02-25 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20180222_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 10, 29, 27, 298895), verbose_name='添加时间'),
        ),
    ]
