# Generated by Django 2.0 on 2018-02-25 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20180225_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 10, 30, 3, 328184), verbose_name='添加时间'),
        ),
    ]
