# Generated by Django 2.0 on 2018-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20180222_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='post',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
